version: '3'
services:
  server:
    build: ./api
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development
    links:
      - db
  web:
    build: ./front
    ports:
      - "3000:3000/tcp"
    volumes:
      - ./front:/app
      - ./front/node_modules:/app/node_modules
  db:
    image: mongo
    ports:
      - '27017:27017'